#!/usr/bin/env bash
# install Install nginx on server, listens on port 80 and
# returns Hello world on querying the server

# update server
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
