#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page

# update server, install and start server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!'> /var/www/html/index.html
SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location /redirect_me {
                rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}"

bash -c "echo -e '$SERVER_CONFIG'> /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
