#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page

# update server, install and start server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!'> /var/www/html/index.html

# Define the server configuration block as a variable
redirect_config = "\nrewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Insert the server configuration block into the default Nginx configuration file using sed
sed -i "s/server_name _;$/redirect_config/" /etc/nginx/sites-available/default

# Restart Nginx
if [ "$(pgrep -c nginx)" -le 0 ];
then
        service nginx start
else
        service nginx restart
fi;
