#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page

# update server, install and start server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!'> /var/www/html/index.html

# Define the server configuration block as a variable
SERVER_CONFIG="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"

# Insert the server configuration block into the default Nginx configuration file using sed
echo "$SERVER_CONFIG"> /etc/nginx/sites-enabled

# Restart Nginx
if [ "$(pgrep -c nginx)" -le 0 ];
then
        service nginx start
else
        service nginx restart
fi;
