#!/usr/bin/env bash
# Configure Nginx with HTTP response containing custom header
# (on web-01 and web-02). Name of the custom HTTP header must be `X-Served-By`
# Value of custom HTTP header must be hostname of the current Nginx server
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu
# machine to the requirements

HEADER_CONFIG="\\\n\t\tadd_header X-Served-By '\$hostname';\n"

# Insert the server configuration block into the default Nginx configuration file using sed
sudo sed -i "49i $HEADER_CONFIG" /etc/nginx/sites-available/default

# Restart Nginx
if [ "$(pgrep -c nginx)" -le 0 ];
then
        sudo service nginx start
else
        sudo service nginx restart
fi;
