#!/usr/bin/env bash
# Configure Nginx with HTTP response containing custom header
# (on web-01 and web-02). Name of the custom HTTP header must be `X-Served-By`
# Value of custom HTTP header must be hostname of the current Nginx server
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu
# machine to the requirements


sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p var/www/html var/www/error
chmod -R 755 /var/www
echo 'Hello World' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

server_config = "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}"



# Use sed to replace the default server block with the new configuration
echo "$server_config"> /etc/nginx/sites-available/default

# Restart nginx
if [ "$(pgrep nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi;

