#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Install stable release of 2.7
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.7 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.7.\* -y

# Backup configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.real.cfg

SERVER_SETUP=(
    '\nfrontend devoye.tech\n'
        '\tbind *:80\n'
        '\tstats uri /haproxy?stats\n'
        '\tdefault_backend http_rear\n'

    '\nbackend devoye.tech\n'
        '\tbalance         roundrobin\n'
        '\tserver web-01 54.236.43.161:80 check\n'
        '\tserver web-02 54.157.177.197:80 check'
)

# Append new config to load balancer
echo -e "${SERVER_SETUP[*]}" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Init file configuration
INIT_FILE='/etc/default/haproxy'

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
        sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
        echo 'ENABLED=1' | sudo tee -a $INIT_FILE > /dev/null
fi

# Restart HAproxy
if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
