#!/usr/bin/env bash
# get MySQL installed on both your web-01 and web-02 servers. v5.7.x
sudo apt-key add signature.key
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get update -y
sudo apt-cache policy mysql-server
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7* -y

# Task 1
sudo mysql
sudo mysql -e "CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';"
sudo mysql -e "GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';"
sudo mysql -e "FLUSH PRIVILEGES;"

