#!/usr/bin/env bash
# get MySQL installed on both your web-01 and web-02 servers. v5.7.x
sudo apt-key add signature.key
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get update -y
sudo apt-cache policy mysql-server
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7* -y

# Task 1
sudo mysql
sudo mysql -e "CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';"
sudo mysql -e "GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';"
sudo mysql -e "FLUSH PRIVILEGES;"
sudo ufw allow from 54.157.177.197 to any port 3306

sudo sed -i 's/^bind-address.*/bind-address\t= 54.157.177.197/' /etc/mysql/mysql.conf.d/mysqld.cnf

echo -e "\nserver-id\t= 1\nlog_bin\t= /var/log/mysql/mysql-bin.log" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf > /dev/null
sudo systemctl restart mysql
 mysql-bin.002524 |      154


# MySQL v 5.7.X other higer versions MASTER = SOURCE
CHANGE MASTER TO
    MASTER_HOST='54.236.43.161',
    MASTER_USER='replica_user',
    MASTER_PASSWORD='projectcorrection280hbtn',
    MASTER_LOG_FILE='mysql-bin.002524',
    MASTER_LOG_POS=154;