#!/usr/bin/env bash
# Configures task 0 to be shorter
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
kill "$(ps aux | pgrep '[n]ginx' | awk '{print $2}')"
