#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
h="0"
i="1"

while [ $h -lt 13 ]
do
    echo "Hour: $h"
    while [ $i -lt 60 ]
    do
        echo $i
        i=$((i+1))
    done
    i="1"
    h=$((h+1))
done