#!/usr/bin/env bash
# script that gives you information about the school file
fi=school

if [ -e "$fi" ]
then
    echo "$fi file exists"
    if [ -s "$fi" ]
    then
        echo "$fi file is not empty"
    else
        echo "$fi file is empty"
    fi
    if [ -f "$fi" ]
    then
        echo "$fi file is a regular file"
    fi
else
    echo "$fi file does not exist"
fi